/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs3354_hello_world;

public class App {
    public String getStarted() {
        return "Getting Started!";
    }

    public static void main(String[] args) {
        int mathresult = 0;
        System.out.println(new App().getStarted());

        Hello greeting = new Hello();
        System.out.println(greeting.sayHello());

        DoMath mathwhiz = new DoMath();
        mathresult = mathwhiz.increment(1);
        System.out.println("Increment result: " + mathresult );
        mathresult = mathwhiz.decrement(mathresult);
        System.out.println("Decrement result: " + mathresult);


        Goodbye thankyou = new Goodbye();
        System.out.println(thankyou.sayGoodbye());
    }
}
